[workspace]
resolver = "2"
members = ["core", "cli"]

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.96"

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros"] }
tokio-util = { version = "0.7", features = ["compat"] }
bolt-client = "0.11"
bolt-proto = "0.12"
chrono = { version = "0.4", default-features = false, features = ["std"] }
chrono-tz = "0.8"
thiserror = "2"
