#pragma once

#include <string>
#include <string_view>
#include <vector>

namespace constants {

// Usage strings
constexpr const auto *kUsage =
    "Memgraph bolt client.\n"
    "The client can be run in interactive or non-interactive mode.\n";

constexpr const std::string_view kInteractiveUsage =
    "In interactive mode, user can enter Cypher queries and supported "
    "commands.\n\n"
    "Cypher queries can span through multiple lines and conclude with a\n"
    "semi-colon (;). Each query is executed in the database and the results\n"
    "are printed out.\n\n"
    "The following interactive commands are supported:\n\n"
    "\t:help\t Print out usage for interactive mode\n"
    "\t:quit\t Exit the shell\n";

constexpr const std::string_view kDocs =
    "If you are new to Memgraph or the Cypher query language, check out these "
    "resources:\n\n"
    "\tQuerying with Cypher:  https://memgr.ph/querying\n"
    "\tImporting data:  https://memgr.ph/importing-data\n"
    "\tDatabase configuration:  https://memgr.ph/configuration\n\n"
    "Official mgconsole documentation available on: "
    "https://memgr.ph/mgconsole\n";

constexpr const std::string_view kCommandQuit = ":quit";
constexpr const std::string_view kCommandHelp = ":help";
constexpr const std::string_view kCommandDocs = ":docs";

// Supported formats.
constexpr const std::string_view kCsvFormat = "csv";
constexpr const std::string_view kTabularFormat = "tabular";
constexpr const std::string_view kCypherlFormat = "cypherl";

// Supported modes.
constexpr const std::string_view kSerialMode = "serial";
constexpr const std::string_view kBatchedParallel = "batched-parallel";
constexpr const std::string_view kParserMode = "parser";

// History default directory.
static const std::string kDefaultHistoryBaseDir = "~";
static const std::string kDefaultHistoryMemgraphDir = ".memgraph";
// History filename.
static const std::string kHistoryFilename = "client_history";

static const std::string kPrompt = "memgraph> ";
static const std::string kMultilinePrompt = "       -> ";

/// Memgraph and OpenCypher keywords.
static const std::vector<std::string_view> kMemgraphKeywords{"ADD",
                                                              "ALTER",
                                                              "ANALYZE",
                                                              "ASYNC",
                                                              "AUTH",
                                                              "BATCH_INTERVAL",
                                                              "BATCH_LIMIT",
                                                              "BATCH_SIZE",
                                                              "BOOTSTRAP_SERVERS",
                                                              "CLEAR",
                                                              "CLUSTER",
                                                              "CONFIG",
                                                              "CONFIGS",
                                                              "CONSTRAINT",
                                                              "CONSTRAINTS",
                                                              "CONSUMER_GROUP",
                                                              "COORDINATOR",
                                                              "CREDENTIALS",
                                                              "CSV",
                                                              "DATA",
                                                              "DATABASE",
                                                              "DATABASES",
                                                              "DELIMITER",
                                                              "DEMOTE",
                                                              "DENY",
                                                              "DISABLE",
                                                              "DROP",
                                                              "DUMP",
                                                              "DURABILITY",
                                                              "ENABLE",
                                                              "ENUM",
                                                              "ENUMS",
                                                              "EXECUTE",
                                                              "EXPLAIN",
                                                              "FAILOVER",
                                                              "FOR",
                                                              "FORCE",
                                                              "FREE",
                                                              "FREE_MEMORY",
                                                              "FROM",
                                                              "GLOBAL",
                                                              "GRANT",
                                                              "GRANTS",
                                                              "GRAPH",
                                                              "HEADER",
                                                              "IDENTIFIED",
                                                              "IMPERSONATE_USER",
                                                              "IN_MEMORY_ANALYTICAL",
                                                              "IN_MEMORY_TRANSACTIONAL",
                                                              "INACTIVE",
                                                              "INDEXES",
                                                              "INFO",
                                                              "INSTANCE",
                                                              "INSTANCES",
                                                              "ISOLATION",
                                                              "KAFKA",
                                                              "KB",
                                                              "KEY",
                                                              "LAG",
                                                              "LEADERSHIP",
                                                              "LEVEL",
                                                              "LICENSE",
                                                              "LOAD",
                                                              "LOCK",
                                                              "LOCK_PATH",
                                                              "MAIN",
                                                              "MB",
                                                              "MEMORY",
                                                              "METRICS",
                                                              "MODE",
                                                              "MODULE_READ",
                                                              "MODULE_WRITE",
                                                              "MULTI_DATABASE_EDIT",
                                                              "MULTI_DATABASE_USE",
                                                              "ON_DISK_TRANSACTIONAL",
                                                              "PASSWORD",
                                                              "PORT",
                                                              "PRIVILEGES",
                                                              "PULSAR",
                                                              "QUOTE",
                                                              "READ_FILE",
                                                              "REGISTER",
                                                              "RENAME",
                                                              "REPLICA",
                                                              "REPLICAS",
                                                              "REPLICATION",
                                                              "RESET",
                                                              "REVOKE",
                                                              "ROLE",
                                                              "ROLES",
                                                              "ROWS",
                                                              "SCHEMA",
                                                              "SERVER",
                                                              "SERVICE_URL",
                                                              "SESSION",
                                                              "SETTING",
                                                              "SETTINGS",
                                                              "SNAPSHOT",
                                                              "SNAPSHOTS",
                                                              "START",
                                                              "STATE",
                                                              "STATISTICS",
                                                              "STATS",
                                                              "STATUS",
                                                              "STOP",
                                                              "STORAGE",
                                                              "STORAGE_MODE",
                                                              "STREAM",
                                                              "STREAMS",
                                                              "STRICT_SYNC",
                                                              "SYNC",
                                                              "TERMINATE",
                                                              "TIMEOUT",
                                                              "TO",
                                                              "TOPICS",
                                                              "TRACE",
                                                              "TRANSACTION",
                                                              "TRANSACTION_MANAGEMENT",
                                                              "TRANSACTIONS",
                                                              "TRANSFORM",
                                                              "TRIGGER",
                                                              "TRIGGERS",
                                                              "TTL",
                                                              "UNIQUE",
                                                              "UNLOCK",
                                                              "UNREGISTER",
                                                              "UPDATE",
                                                              "USAGE",
                                                              "USE",
                                                              "USER",
                                                              "USERS",
                                                              "VERSION"};

static const std::vector<std::string_view> kCypherKeywords{"AFTER",
                                                            "ALL",
                                                            "AND",
                                                            "ANY",
                                                            "AS",
                                                            "ASC",
                                                            "ASCENDING",
                                                            "ASSERT",
                                                            "AT",
                                                            "BEFORE",
                                                            "BOOLEAN",
                                                            "BUILD",
                                                            "BY",
                                                            "CALL",
                                                            "CASE",
                                                            "CHECK",
                                                            "COALESCE",
                                                            "COMMITTED",
                                                            "CONTAINING",
                                                            "CONTAINS",
                                                            "COUNT",
                                                            "CREATE",
                                                            "CURRENT",
                                                            "DATE",
                                                            "DELETE",
                                                            "DESC",
                                                            "DESCENDING",
                                                            "DETACH",
                                                            "DIRECTORY",
                                                            "DISTINCT",
                                                            "DO",
                                                            "DURATION",
                                                            "EDGE",
                                                            "EDGES",
                                                            "EDGE_TYPES",
                                                            "ELSE",
                                                            "END",
                                                            "ENDS",
                                                            "EVERY",
                                                            "EXACTLY",
                                                            "EXISTS",
                                                            "EXTRACT",
                                                            "FALSE",
                                                            "FILTER",
                                                            "FLOAT",
                                                            "FOREACH",
                                                            "HOPS",
                                                            "IF",
                                                            "IGNORE",
                                                            "IMPORT",
                                                            "IN",
                                                            "INDEX",
                                                            "INTEGER",
                                                            "IS",
                                                            "KSHORTEST",
                                                            "LABELS",
                                                            "LIMIT",
                                                            "LIST",
                                                            "LOCALDATETIME",
                                                            "LOCALTIME",
                                                            "MAP",
                                                            "MATCH",
                                                            "MATCHING",
                                                            "MERGE",
                                                            "NEXT",
                                                            "NO",
                                                            "NODE",
                                                            "NODES",
                                                            "NODE_LABELS",
                                                            "NONE",
                                                            "NOT",
                                                            "NOTHING",
                                                            "NULL",
                                                            "NULLIF",
                                                            "OFF",
                                                            "OF_TOKEN",
                                                            "ON",
                                                            "OPTIONAL",
                                                            "OR",
                                                            "ORDER",
                                                            "PARQUET",
                                                            "PERIODIC",
                                                            "POINT",
                                                            "PROCEDURE",
                                                            "PROCEDURES",
                                                            "PROFILE",
                                                            "PROFILES",
                                                            "PROFILE_RESTRICTION",
                                                            "QUERY",
                                                            "READ",
                                                            "RECOVER",
                                                            "REDUCE",
                                                            "REMOVE",
                                                            "REPLACE",
                                                            "RESOURCE",
                                                            "RETURN",
                                                            "SET",
                                                            "SHOW",
                                                            "SINGLE",
                                                            "SKIP",
                                                            "STARTS",
                                                            "STRING",
                                                            "TEXT",
                                                            "THEN",
                                                            "TRUE",
                                                            "TYPED",
                                                            "TYPES",
                                                            "UNCOMMITTED",
                                                            "UNION",
                                                            "UNLIMITED",
                                                            "UNWIND",
                                                            "USING",
                                                            "VALUE",
                                                            "VALUES",
                                                            "VECTOR",
                                                            "WEBSOCKET",
                                                            "WHEN",
                                                            "WHERE",
                                                            "WITH",
                                                            "XOR",
                                                            "YIELD"};

static const std::vector<std::string_view> kAwesomeFunctions{"ABS",
                                                             "ACOS",
                                                             "ASIN",
                                                             "ASSERT",
                                                             "ATAN",
                                                             "ATAN2",
                                                             "CEIL",
                                                             "COS",
                                                             "COUNTER",
                                                             "DATE",
                                                             "DATETIME",
                                                             "DEGREE",
                                                             "DURATION",
                                                             "E",
                                                             "ENDNODE",
                                                             "EXP",
                                                             "FLOOR",
                                                             "FROMBYTESTRING",
                                                             "GETHOPSCOUNTER",
                                                             "HEAD",
                                                             "INDEGREE",
                                                             "ISEMPTY",
                                                             "KEYS",
                                                             "LABELS",
                                                             "LAST",
                                                             "LEFT",
                                                             "LENGTH",
                                                             "LOCALDATETIME",
                                                             "LOCALTIME",
                                                             "LOG",
                                                             "LOG10",
                                                             "LTRIM",
                                                             "NODES",
                                                             "OUTDEGREE",
                                                             "PI",
                                                             "POINT",
                                                             "POINT.DISTANCE",
                                                             "POINT.WITHINBBOX",
                                                             "PROPERTIES",
                                                             "PROPERTYSIZE",
                                                             "RAND",
                                                             "RANDOMUUID",
                                                             "RANGE",
                                                             "RELATIONSHIPS",
                                                             "REPLACE",
                                                             "REVERSE",
                                                             "RIGHT",
                                                             "ROUND",
                                                             "RTRIM",
                                                             "SIGN",
                                                             "SIN",
                                                             "SPLIT",
                                                             "SQRT",
                                                             "STARTNODE",
                                                             "SUBSTRING",
                                                             "TAIL",
                                                             "TAN",
                                                             "TIMESTAMP",
                                                             "TOBOOLEAN",
                                                             "TOBYTESTRING",
                                                             "TOENUM",
                                                             "TOFLOAT",
                                                             "TOINTEGER",
                                                             "TOLOWER",
                                                             "TOSET",
                                                             "TOSTRING",
                                                             "TOSTRINGORNULL",
                                                             "TOUPPER",
                                                             "TRIM",
                                                             "TYPE",
                                                             "UNIFORMSAMPLE",
                                                             "VALUES",
                                                             "VALUETYPE"};

}  // namespace constants
