import mgclient


def connect_to_memgraph(
    host="127.0.0.1", port=7687, user="memgraph", password="memgraph"
):
    conn = mgclient.connect(
        host=host,
        port=port,
        username=user,
        password=password,
    )
    return conn


def fetch_sql_metadata(sql_system_name):
    conn = connect_to_memgraph()
    cursor = conn.cursor()
    cursor.execute(f"CALL {sql_system_name}.get_metadata() YIELD *")
    results = cursor.fetchall()
    cursor.close()
    conn.close()
    return results


def fetch_sql_table(sql_system_name, table):
    conn = connect_to_memgraph()
    cursor = conn.cursor()
    cursor.execute(f"CALL {sql_system_name}.migrate('{table}') YIELD *")
    results = cursor.fetchall()
    cursor.close()
    conn.close()
    return results


if __name__ == "__main__":
    sql_system = "mysql"  # Replace with your SQL system name
    metadata = fetch_sql_metadata(sql_system)
    # TODO(gitbuda): Ask LLM to determine what's the right table / graph format.
    print("Fetched metadata:")
    for row in metadata:
        print(row)
    data = fetch_sql_table(sql_system, "users")
    print("Fetched data:")
    for row in data:
        print(row)


# CALL metadata() YIELD tables
# -> LLM decideds what are relevant tables
# WITH relevant_metadata # NOTE: it has to be a single variable (a map) -> inject YES/NO.
# CALL migrate(relevant_metadata["table1"]) AS row # this is going to be called N times...
#     custom code 0 -> generated by LLM
# CALL migrate(relevant_metadata["tableN"]) AS row
#     custom code N -> generated by LLM
