name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest memgraph image
        run: |
          docker pull memgraph/memgraph:latest
          echo "MEMGRAPH_IMAGE=memgraph/memgraph:latest" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Install and test mgconsole
        run: |
          cmake -B build -G Ninja -DMEMGRAPH_USE_DOCKER=ON -DMEMGRAPH_DOCKER_IMAGE=$MEMGRAPH_IMAGE
          cmake --build build
          sudo cmake --install build
          ctest --verbose --test-dir build
      - name: Save mgconsole test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "mgconsole_ctest.log"
          path: build/Testing/Temporary/LastTest.log 

  build_windows_mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set-up repository
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
      - name: Build and install mgconsole
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --parallel
          cmake --install build
      - name: Save mgconsole Windows build
        uses: actions/upload-artifact@v4
        with:
          name: "mgconsole Windows build"
          path: build/src/mgconsole.exe

  build_apple:
    runs-on: macos-latest
    steps:
      - name: Set-up repository
        uses: actions/checkout@v4
      # NOTE: CI can't execute end2end tests because there is no way to run
      #       Memgraph on CI MacOS machines.
      - name: Install openssl
        run: |
          brew update
          brew install openssl
      - name: Build mgconsole
        run: |
          cmake -B build -G Ninja -DOPENSSL_ROOT_DIR="$(brew --prefix openssl)" -DCMAKE_BUILD_TYPE=Release .
          cmake --build build
      - name: Save mgconsole MacOS build
        uses: actions/upload-artifact@v4
        with:
          name: "mgconsole MacOS build"
          path: build/src/mgconsole

  build_and_test_static:
    strategy:
      matrix:
        arch: [X64, ARM64]
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}" ]
    steps:
      - uses: actions/checkout@v4

      - name: build mgconsole static
        run: |
          ./build-generic-linux.sh

      - name: Save mgconsole static build
        uses: actions/upload-artifact@v4
        with:
          name: "mgconsole static Linux build ${{ matrix.arch }}"
          path: build/generic/mgconsole

      - name: Pull latest memgraph image
        run: |
          docker pull memgraph/memgraph:latest
          echo "MEMGRAPH_IMAGE=memgraph/memgraph:latest" >> $GITHUB_ENV

      - name: Test mgconsole static build
        run: |
          ./tests/test-static.sh --docker $MEMGRAPH_IMAGE build/generic/mgconsole
          ./tests/test-static.sh --use-ssl --docker $MEMGRAPH_IMAGE build/generic/mgconsole
