name: CI

on: 
  push:
  workflow_dispatch:
    inputs:
      buil-static:
        description: "Build static version of mgconsole"
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      build-static:
        description: "Build static version of mgconsole"
        type: boolean
        required: false
        default: false

run-name: "CI: Build and test mgconsole"

jobs:
  build_and_test_ubuntu:
    name: Build and test mgconsole on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest memgraph image
        run: |
          docker pull memgraph/memgraph:latest
          echo "MEMGRAPH_IMAGE=memgraph/memgraph:latest" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install and test mgconsole
        run: |
          cmake -B build -G Ninja -DMEMGRAPH_USE_DOCKER=ON -DMEMGRAPH_DOCKER_IMAGE=$MEMGRAPH_IMAGE
          cmake --build build
          sudo cmake --install build
          ctest --verbose --test-dir build

      - name: Save mgconsole test results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: "mgconsole_ctest.log"
          path: build/Testing/Temporary/LastTest.log 

  build_windows_mingw:
    name: Build and test mgconsole on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set-up repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda  # v2.30.0
        with:
          msystem: MINGW64
          update: true
          install: >-
            git base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl

      - name: Build and install mgconsole
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --parallel
          cmake --install build

      - name: Save mgconsole Windows build
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: "mgconsole Windows build"
          path: build/src/mgconsole.exe

  build_apple:
    name: Build and test mgconsole on Apple
    runs-on: macos-latest
    steps:
      - name: Set-up repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      # NOTE: CI can't execute end2end tests because there is no way to run
      #       Memgraph on CI MacOS machines.

      - name: Install openssl
        run: |
          brew update
          brew install openssl

      - name: Build mgconsole
        run: |
          cmake -B build -G Ninja -DOPENSSL_ROOT_DIR="$(brew --prefix openssl)" -DCMAKE_BUILD_TYPE=Release .
          cmake --build build
          sudo cmake --install build

      - name: Save mgconsole MacOS build
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: "mgconsole MacOS build"
          path: build/src/mgconsole

  build_and_test_static:
    if: ${{ inputs.build-static }}
    name: Build and test mgconsole static build
    strategy:
      fail-fast: false
      matrix:
        arch: [X64, ARM64]
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}" ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: build mgconsole static
        run: |
          ./build-generic-linux.sh

      - name: Save mgconsole static build
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: "mgconsole static Linux build ${{ matrix.arch }}"
          path: build/generic/mgconsole

      - name: Pull latest memgraph image
        run: |
          docker pull memgraph/memgraph:latest
          echo "MEMGRAPH_IMAGE=memgraph/memgraph:latest" >> $GITHUB_ENV

      - name: Test mgconsole static build
        run: |
          ./tests/test-static.sh --docker $MEMGRAPH_IMAGE
          ./tests/test-static.sh --use-ssl --docker $MEMGRAPH_IMAGE

      - name: Cleanup docker images
        run: |
          docker rmi $MEMGRAPH_IMAGE || true
          if [[ "${{ matrix.arch }}" == "X64" ]]; then
            docker rmi memgraph/mgbuild:v7_centos-9 || true
          elif [[ "${{ matrix.arch }}" == "ARM64" ]]; then
            docker rmi memgraph/mgbuild:v7_debian-12-arm || true
          fi
